[package]
name = "aggregate-client"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
[features]
engine-tracing = ["bevy/trace"]
[dependencies]
bevy.workspace = true
aggregate-ui.workspace = true
aggregate-localization.workspace = true
aggregate-simulation-core.workspace = true
aggregate-scenario.workspace = true
aggregate-world.workspace = true
aggregate-map-view.workspace = true
aggregate-programs.workspace = true
uuid.workspace = true
ron.workspace = true
anyhow = "1.0.104"
tracing.workspace = true
tracing-subscriber.workspace = true
tracing-appender.workspace = true
[lints]
workspace = true
