[package]
name = "aggregate-economy"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
aggregate-world.workspace = true
aggregate-programs.workspace = true
aggregate-scenario.workspace = true
bevy_ecs.workspace = true
serde_json.workspace = true
tracing.workspace = true

[dev-dependencies]
uuid.workspace = true

[lints]
workspace = true
