[package]
name = "aggregate-programs"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
aggregate-world.workspace = true
aggregate-scenario.workspace = true
bevy_ecs.workspace = true
serde.workspace = true
serde_json.workspace = true
semver.workspace = true
tracing.workspace = true

[lints]
workspace = true
